name: UIClasses Tests
on: [push, pull_request]

jobs:
  python:
    name: "Python"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - "3.6"
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"

    steps:
    - uses: actions/checkout@v3
    - name: Install python version
      uses: gabrielfalcao/pyenv-action@v15
      with:
        default: "${{ matrix.python }}"
        command: pip install -U pip setuptools

    - name: Install Dependencies
      uses: gabrielfalcao/pyenv-action@v15
      with:
        default: "${{ matrix.python }}"
        command: pip install -r development.txt

    - name: Install Dependencies
      uses: gabrielfalcao/pyenv-action@v15
      with:
        default: "${{ matrix.python }}"
        command: pip install -e .

    - name: Execute Tests
      uses: gabrielfalcao/pyenv-action@v15
      with:
        default: "${{ matrix.python }}"
        command: make test
