name: UIClasses Tests
on: [push, pull_request]

jobs:
  python:
    name: "Python"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - "3.7.16"
          - "3.8.16"
          - "3.9.16"
          - "3.6.15"

    steps:
    - uses: actions/checkout@v3
    - name: Install Dependencies
      uses: gabrielfalcao/pyenv-action@v16
      with:
        default: "${{ matrix.python }}"
        command: |
          pip install -U pip setuptools
          pip install -r development.txt
          pip install -e .

    - name: Execute Tests
      run: pyenv local "${{ matrix.python }}" && python --version && make tests

    - id: bento
      name: Bento Ack
      uses: returntocorp/bento-action@v1
      with:
        acceptTermsWithEmail: gabriel@nacaolivre.org
